name: element_embedding
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '3.0.0-218.1.beta <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.6
#  permission_handler:
#  slider_button: ^2.0.0
#  animated_bottom_navigation_bar: ^0.3.2
#  carousel_slider: ^4.0.0
#  fdottedline:
#  dotted_border: ^2.0.0+1
#  cached_network_image: ^3.1.0
#  dotted_line: ^3.0.1
#  popup_menu:
#  scrollable_positioned_list: ^0.2.3
#  scroll_to_index: ^2.1.1
#  scratcher:
#  confetti:
#  grouped_buttons:
#  upgrader:
#  lottie: ^2.1.0
#  scrollable_list_tab_scroller:
#  # The following adds the Cupertino Icons font to your application.
#  # Use with the CupertinoIcons class for iOS style icons.
#
#  auto_size_text: ^3.0.0-nullsafety.0
#  built_collection: ^5.1.0
#  built_value: ^8.1.1
#  cloud_firestore: ^3.1.6
#  shimmer: ^2.0.0
#  firebase_auth: ^3.3.5
#  firebase_core: ^1.11.0
#  flutter_animated_cards: ^0.0.2
#  change_app_package_name: ^1.1.0
#  flutter_datetime_picker: ^1.5.1
#  flutter_facebook_auth: ^4.0.1
#  font_awesome_flutter: ^9.1.0
#  geolocator: ^7.4.0
#  google_fonts: ^2.1.0
#  google_sign_in: ^5.0.5
#  intl: ^0.17.0
#  json_serializable: ^6.1.3
#  page_transition: ^2.0.2
#  rxdart: ^0.27.1
#  sign_in_with_apple: ^3.0.0
#  smooth_page_indicator: ^1.0.0+2
#  flutter_rating_bar: ^4.0.0
#  url_launcher:
#  mime_type: ^1.0.0
#  carousel_pro:
#  firebase_storage: ^10.0.1
#  firebase_messaging: ^11.2.4
#  connectivity: ^3.0.6
#  timeago: ^3.1.0
#  flutter_screenutil: ^5.0.0+2
#  awesome_dialog: ^2.1.0
#  geocoding: ^2.0.0
#  google_maps_flutter: ^2.0.6
#  firebase_crashlytics: ^2.1.1
#  #  firebase_performance: ^0.8.0+3
#  geolocator_android:
#  flutter_local_notifications: ^9.0.2
#  google_maps_place_picker: ^2.1.0-nullsafety.3
#  flutter_svg: ^1.0.0
#  pinput: ^1.2.2
#  sms_autofill: ^2.2.0
#  google_place: ^0.4.3
  rounded_loading_button: ^2.0.9
#  fluttertoast: ^8.0.8
#  collection: ^1.16.0
#  draggable_home: ^1.0.3
#  cashfree:
#  flutter_bounce: ^1.1.0
#  cashfree_pg: ^2.0.4+24
#  upi_india: ^3.0.1
#  #  flutter_cashfree_pg_sdk: ^2.0.4+7
#  animated_widgets: ^1.1.0
#  scrollable_list_tabview:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/dash.png
    - assets/foodzer logo (2).png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
